services:
  emoncms:
    image: alexjunk/themis:alpine3.18_emoncms11.4.7
    environment:
      - TZ=Europe/Paris
      - REDIS_BUFFER=1
      - EMONCMS_LOG_LEVEL=2
      - MYSQL_DATABASE=emoncms
      - MYSQL_USER=emoncms
      - MYSQL_PASSWORD=emonpiemoncmsmysql2016
      - MQTT_USER=emonpi
      - MQTT_PASSWORD=emonpimqtt2016
      - MQTT_HOST=localhost
      - MQTT_LOG_LEVEL=error
      - CRT_FILE=/etc/ssl/apache2/server.pem
      - KEY_FILE=/etc/ssl/apache2/server.key
      - CNAME=localhost
    ports:
      - 8081:80
      - 8082:443
      - 7883:1883
    restart: always
